[en]
  weight = 10
  disabled = false
  contentDir = "content/en"
  languageCode = "en"
  languageName = "English"
  hasCJKLanguage = false
  copyright = "This work is licensed under CC BY-NC-SA-4.0."
[zh-CN]
  weight = 20
  disabled = false
  contentDir = "content/zh-cn"
  languageCode = "zh-CN"
  languageName = "简体中文"
  hasCJKLanguage = true
  copyright = "本站内容采用 CC BY-NC-SA 4.0 国际许可协议。"